### ISSUE TITLE
4.2.3 Assignment Notebook: typo confusing sentence meaning

### ISSUE THREAD

**Issue by lineality** [LambdaSchool/DS-Unit-4-Sprint-2-Neural-Networks#131]
The following "sentence" is not grammatically correct and fixing it in various ways changes the meaning of the sentence in various ways. What should this sentence say?

"Make sure to have your final layer have as many nodes as the number of classes that you want to predict."

**Comment by sokjc** [comment]
Will update to say: 

> The number of nodes in your output layer should equal the number of classes you want to predict for Fashion-MNIST.
