### ISSUE TITLE
Incorrect Sigmoid derivative function in module 2

### ISSUE THREAD

**Issue by Phatdeluxe** [LambdaSchool/DS-Unit-4-Sprint-2-Neural-Networks#134]
In module2-backpropagation/LS_DS_422_Gradient_Descent_Backprop_Lecture.ipynb the sidmoid derivative function (sigmoidPrime) is calculated incorrectly. 
It currently is:
```
def sigmoidPrime(self, s):
     return s * (1 - s) 
```
and it should be:
```
def sigmoidPrime(self, s):
     sx = sigmoid(s)
     return sx * (1 - sx)
```

This class function can be found under the header 'Update Weights Based on Gradient'

**Comment by sokjc** [comment]
This issue has been resolved in a previous commit.
